name: Run

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Direct URL to file"
        required: true
      ending:
        description: "Fileending"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Convert YouTube to File
        run: |
          sudo apt update
          sudo apt install -y git libopencv-dev clang libclang-dev libssl-dev

          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source "$HOME/.cargo/env"
          
          git clone https://github.com/DvorakDwarf/Infinite-Storage-Glitch.git
          cd Infinite-Storage-Glitch/
          cargo build --release
          cd target/release/
          ./isg_4real download -u "${{ github.event.inputs.url }}"
          mv *.mp4 file.mp4
          
          ./isg_4real dislodge -i file.mp4 -o ${{ github.workspace }}/file"${{ github.event.inputs.ending }}"
          

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: file
          path: ${{ github.workspace }}/file"${{ github.event.inputs.ending }}"
